### ISSUE TITLE
Google Colab webui problem

### ISSUE THREAD

**Issue by 1111dontworryaboutit** [TheLastBen/fast-stable-diffusion#2075]
Hello everyone!

Running stable diffusion on Google Colab.
Until now I have not faced any issues with Automatic1111, except for some Dreambooth bugs, but that's another story.
So about one hour ago I started getting errors, and since then no matter if I ran stable diffusion with "Use_Latest_Working_Commit" checked or not, or running stable diffusion through a tunnel works. Also doesn't matter which model I am loading, as even with the original ones I get this type of errors : 

*Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 15, in <module>
    from modules import paths, timer, import_hook, errors
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/paths.py", line 4, in <module>
    from modules.paths_internal import models_path, script_path, data_path, extensions_dir, extensions_builtin_dir
ModuleNotFoundError: No module named 'modules.paths_internal'*

Any help or ideas? I have tried many things and nothing works still, getting kinda frustrated...

**Comment by TheLastBen** [comment]
remove the sd folder and try again with the latest notebook https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by Fronscavenger** [comment]
!pip install gradio_client
!pip install -U gradio

**Comment by 1111dontworryaboutit** [comment]
Most things were satisfied, but I got this error after running these commands : *ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rembg 2.0.30 requires asyncer~=0.0.2, which is not installed.
rembg 2.0.30 requires filetype~=1.2.0, which is not installed.
rembg 2.0.30 requires imagehash~=4.3.1, which is not installed.
rembg 2.0.30 requires watchdog~=2.1.9, which is not installed.
rembg 2.0.30 requires fastapi~=0.87.0, but you have fastapi 0.88.0 which is incompatible.
rembg 2.0.30 requires numpy~=1.23.5, but you have numpy 1.22.4 which is incompatible.
rembg 2.0.30 requires onnxruntime~=1.13.1, but you have onnxruntime 1.14.1 which is incompatible.
rembg 2.0.30 requires opencv-python-headless~=4.6.0.66, but you have opencv-python-headless 4.7.0.72 which is incompatible.
rembg 2.0.30 requires pillow~=9.3.0, but you have pillow 8.4.0 which is incompatible.
rembg 2.0.30 requires scipy~=1.9.3, but you have scipy 1.10.1 which is incompatible.
rembg 2.0.30 requires tqdm~=4.64.1, but you have tqdm 4.65.0 which is incompatible.
rembg 2.0.30 requires uvicorn~=0.20.0, but you have uvicorn 0.18.3 which is incompatible.*




and when triying to run Stable Diffusion - this error :  *Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 22, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 23, in <module>
    from gradio import (
ImportError: cannot import name 'encryptor' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/gradio/__init__.py)*

**Comment by TheLastBen** [comment]
use the latest notebook

**Comment by modulator** [comment]
Same

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by ubranch** [comment]
Same error

```ControlNet v1.1.129
ControlNet v1.1.129
Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: 43c90409bd4493ea9f4734a166fc6180913f97cef4f69a2b7883edf700779693
Loading weights [43c90409bd] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stablediffusion/configs/stable-diffusion/v2-inference-v.yaml
LatentDiffusion: Running in v-prediction mode
DiffusionWrapper has 865.91 M params.
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 86.2s (calculate hash: 53.7s, load weights from disk: 20.3s, find config: 5.4s, load config: 0.2s, create model: 0.4s, apply weights to model: 3.3s, apply half(): 1.7s, move model to device: 1.2s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'```

**Comment by TheLastBen** [comment]
fixed in the latest commit

**Comment by neriiacopo** [comment]
Before throwing another allarm that things are yet not working, thank you for all the troubleshooting! It must be pretty intense to keep up the A1111 on Colab up to date with all the amazing stuff being created on a daily basis...

I am afraid I still need to point out that the bug persists even with the latest commit.

I can bypass the trigger_after bug by avoiding the latest_commit, yet this solution fails to create an endpoint for the api (/docs also failing as pointed out yesterday).

With latest_working_commit bug persists, indipendently of 
- the connection to my Drive (not running first cell) 
- CloudFare server on/off
- Controlnet

and throws:

ControlNet v1.1.132
ControlNet v1.1.132
Calculating sha256 for /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt: 4c86efd062ea772972dd068c3870773f1fd9a37ba9a288ee79ec848448ce7785
Loading weights [4c86efd062] from /content/gdrive/MyDrive/sd/stable-diffusion-webui/models/Stable-diffusion/model.ckpt
Creating model from config: /content/gdrive/MyDrive/sd/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Downloading (…)olve/main/vocab.json100% 961k/961k [00:00<00:00, 120MB/s]
Downloading (…)olve/main/merges.txt100% 525k/525k [00:00<00:00, 63.8MB/s]
Downloading (…)cial_tokens_map.json100% 389/389 [00:00<00:00, 583kB/s]
Downloading (…)okenizer_config.json100% 905/905 [00:00<00:00, 1.28MB/s]
Downloading (…)lve/main/config.json100% 4.52k/4.52k [00:00<00:00, 5.69MB/s]
Applying scaled dot product cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 30.9s (calculate hash: 8.3s, load weights from disk: 15.2s, create model: 1.8s, apply weights to model: 3.4s, apply half(): 1.3s, move model to device: 0.9s).
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 337, in <module>
    webui()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 240, in webui
    shared.demo = modules.ui.create_ui();shared.demo.queue(concurrency_count=999999,status_update_rate=0.1)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 461, in create_ui
    txt2img_prompt, txt2img_prompt_styles, txt2img_negative_prompt, submit, _, _, txt2img_prompt_style_apply, txt2img_save_style, txt2img_paste, extra_networks_button, token_counter, token_button, negative_token_counter, negative_token_button = create_toprow(is_img2img=False)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/ui.py", line 309, in create_toprow
    skip.click(
  File "/usr/local/lib/python3.10/dist-packages/gradio/events.py", line 129, in __call__
    dep, dep_index = self.trigger.set_event_trigger(
TypeError: Block.set_event_trigger() got an unexpected keyword argument 'trigger_after'

**Comment by TheLastBen** [comment]
try running the notebook from the link and without the first cell

**Comment by TintaViva** [comment]
Hi, i just try the new commit, but keeps failing, a "Google drive error" pop-up appears and disconnects
Any idea or solution?

**Comment by noahsilverado** [comment]
I guess it's over for us peasants. The webui lasted just 6 minutes for me. It keeps getting disconnected.

**Comment by neriiacopo** [comment]
> try running the notebook from the link and without the first cell
Running first cell or not was inunfluential at the time of writing.

Yet now I can successfully launch and call from the API, thank you for the support!
Everything works smoothly like it used to!

**Comment by Tonkatsu-01** [comment]
hi guys, any update if the colab is working back noramally?

**Comment by magicgearco** [comment]
Hi, when I run the colab this error pop up "google drive error has occurred" 
Then program not working, I tried with different emails, but same error happened. 

Is this happen to anyone?

**Comment by saumil92001** [comment]
> hi guys, any update if the colab is working back noramally?

Yeah guys plz let us know if there any...

**Comment by TintaViva** [comment]
> > try running the notebook from the link and without the first cell
> > Running first cell or not was inunfluential at the time of writing.
> 
> Yet now I can successfully launch and call from the API, thank you for the support! Everything works smoothly like it used to!



> try running the notebook from the link and without the first cell

Great, it works, how about the models, how can i use my models with this solution?

**Comment by saumil92001** [comment]
> hi guys, any update if the colab is working back noramally?

Yes guys plz let us know :(
