### ISSUE TITLE
ImportError: cannot import name 'analytics' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/gradio/__init__.py)

### ISSUE THREAD

**Issue by noha2310** [TheLastBen/fast-stable-diffusion#2284]
ImportError: cannot import name 'analytics' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/gradio/__init__.py)

What should I do?

**Comment by TheLastBen** [comment]
I'll check it out

**Comment by TheLastBen** [comment]
try with the latest notebook

**Comment by lyrium** [comment]
Had the same problem as OP, now getting this:

```
Stable diffusion model failed to load
Loading weights [bb6e6362d8] from /models/model.ckpt
Loading weights [bb6e6362d8] from /models/model.ckpt
loading stable diffusion model: UnpicklingError
Traceback (most recent call last):
  File "/notebooks/sd/stable-diffusion-webui/modules/processing.py", line 607, in process_images
    sd_models.reload_model_weights()
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 544, in reload_model_weights
    state_dict = get_checkpoint_state_dict(checkpoint_info, timer)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 271, in get_checkpoint_state_dict
    res = read_state_dict(checkpoint_info.filename)
  File "/notebooks/sd/stable-diffusion-webui/modules/sd_models.py", line 252, in read_state_dict
    pl_sd = torch.load(checkpoint_file, map_location=map_location or shared.weight_load_location)
  File "/notebooks/sd/stable-diffusion-webui/modules/safe.py", line 108, in load
    return load_with_extra(filename, *args, extra_handler=global_extra_handler, **kwargs)
  File "/notebooks/sd/stable-diffusion-webui/modules/safe.py", line 156, in load_with_extra
    return unsafe_torch_load(filename, *args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.9/dist-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '\xec'.
```

**Comment by TheLastBen** [comment]
check your model, make sure you tick the right box if it's safetensors or not

**Comment by noha2310** [comment]
Mrs. TheLastBen.
Thanks to you, the error was resolved.

Thank you so much. ^ _ ^

**Comment by IkkoKojima** [comment]
I was getting the same error. 
I changed the fast_stable_diffusion_AUTOMATIC1111 repository to the latest one and the error went away.

**Comment by hey12344321** [comment]
Requirement already satisfied: tomesd in /usr/local/lib/python3.10/dist-packages (0.1.3)
Requirement already satisfied: torch>=1.12.1 in /usr/local/lib/python3.10/dist-packages (from tomesd) (2.0.1+cu118)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.12.1->tomesd) (3.12.2)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.12.1->tomesd) (4.6.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.12.1->tomesd) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.12.1->tomesd) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.12.1->tomesd) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.12.1->tomesd) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.12.1->tomesd) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.12.1->tomesd) (16.0.6)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.12.1->tomesd) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.12.1->tomesd) (1.3.0)
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 35, in <module>
    import gradio
  File "/usr/local/lib/python3.10/dist-packages/gradio/__init__.py", line 3, in <module>
    import gradio.components as components
  File "/usr/local/lib/python3.10/dist-packages/gradio/components.py", line 56, in <module>
    from gradio.blocks import Block, BlockContext
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 26, in <module>
    from gradio import (
ImportError: cannot import name 'analytics' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/gradio/__init__.py)

same here

**Comment by omar3737** [comment]
still receiving this error after using latest notebook, are these settings correct? 
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/137326496/501ae9b8-e041-4187-9e11-9ab67efb9b80)

**Comment by omar3737** [comment]
this is the error im getting 
![image](https://github.com/TheLastBen/fast-stable-diffusion/assets/137326496/3ecd4af5-c456-4335-8518-01e1938509bc)

**Comment by hey12344321** [comment]
> this is the error im getting ![image](https://user-images.githubusercontent.com/137326496/249175803-3ecd4af5-c456-4335-8518-01e1938509bc.png)

It's the notebook problem, i'm still getting error even i create a new google account.

**Comment by TheLastBen** [comment]
rename your old sd folder to sd_old

**Comment by draxx318** [comment]
> rename your old sd folder to sd_old

I am still getting the same error as the others after renaming and installing a fresh copy.

**Comment by zhourunfaLi** [comment]
use the latest notebook and delete the model.ckpt

**Comment by TheLastBen** [comment]
@draxx318 https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
try running it without the first cell

**Comment by draxx318** [comment]
@TheLastBen 
I will try. I copied a model from the old sd folder to the new one, perhaps that could be the issue. Im going to try both solutions later.

**Comment by draxx318** [comment]
Running the last notebook and redownloading the model worked for me.

**Comment by Lightray999** [comment]
Had the same issues as reported here by the original op.  I reloaded a new collab notebook of Stable Diffusion.  Didn't understand this at first but figured it out. Just means you load collab Stable Diffusion again from the source where you got it. Didn't need to rename or delete anything from my end.  Kept my directory structure the same. Somehow I guess changes done in the source level (Collab notebook) changed so we needed to load again from the source.  Hope this helps some people.

**Comment by StewartSethA** [comment]
> ImportError: cannot import name 'analytics' from partially initialized module 'gradio' (most likely due to a circular import) (/usr/local/lib/python3.10/dist-packages/gradio/**init**.py)
> 
> What should I do?

Is your python script named the same as one of its import libraries? This is how I inadvertently caused this issue.
