### ISSUE TITLE
Error when starting Stable Difussion

### ISSUE THREAD

**Issue by ruisutz** [TheLastBen/fast-stable-diffusion#3020]
i restarted the runtime environment but when i start again i get this error

```
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/webui.py", line 13, in <module>
    initialize.imports()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/initialize.py", line 17, in imports
    import pytorch_lightning  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/__init__.py", line 34, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/callbacks/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks.pruning import ModelPruning
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/callbacks/pruning.py", line 30, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/core/__init__.py", line 16, in <module>
    from pytorch_lightning.core.module import LightningModule
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/core/module.py", line 41, in <module>
    from pytorch_lightning.loggers import Logger, LoggerCollection
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/loggers/__init__.py", line 24, in <module>
    from pytorch_lightning.loggers.wandb import WandbLogger  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pytorch_lightning/loggers/wandb.py", line 34, in <module>
    import wandb
  File "/usr/local/lib/python3.11/dist-packages/wandb/__init__.py", line 27, in <module>
    from wandb import sdk as wandb_sdk
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/__init__.py", line 4, in <module>
    from .artifacts.artifact import Artifact  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/artifacts/artifact.py", line 36, in <module>
    from wandb.apis.normalize import normalize_exceptions
  File "/usr/local/lib/python3.11/dist-packages/wandb/apis/__init__.py", line 43, in <module>
    from .internal import Api as InternalApi  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wandb/apis/internal.py", line 3, in <module>
    from wandb.sdk.internal.internal_api import Api as InternalApi
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/internal/internal_api.py", line 48, in <module>
    from ..lib import retry
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/retry.py", line 17, in <module>
    from .mailbox import ContextCancelledError
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/mailbox.py", line 102, in <module>
    class _MailboxSlot:
  File "/usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/mailbox.py", line 103, in _MailboxSlot
    _result: Optional[pb.Result]
                      ^^^^^^^^^
AttributeError: module 'wandb.proto.wandb_internal_pb2' has no attribute 'Result'
```

I already tried a clean install as well

**Comment by Zylixen** [comment]
same

**Comment by Momo3945** [comment]
Happening to me too

**Comment by wave1116** [comment]
I have the same symptoms

**Comment by rori54** [comment]
It's not working again. It seems to be the same error as a few days ago. 😯

**Comment by BlessedDuel** [comment]
damn! same problem xD

**Comment by Tauri7752** [comment]
Same thing. Yesterday, everything worked

**Comment by da-art-fantasy** [comment]
AttributeError: module 'wandb.proto.wandb_internal_pb2' has no attribute 'Result'

Same thing. Yesterday, everything worked

**Comment by ruisutz** [comment]
> Didn't have time to test yet if downgrading protobuf alone is enough, and upgrading wandb perhaps unnecessary, but I went around it with this for now (run somewhere between **Requirements** cell and **Start Stable-Diffusion** cell):
> 
> ```
> !pip install protobuf==3.20 --no-deps
> !pip install wandb==0.16.6 --no-deps
> ```
> 
> Colab will tell you to restart runtime after this, but no need to restart.

This fix worked for me, thank you very much
hopefully there will be a patch soon

**Comment by mdlieber99** [comment]
that code (protobuf & wandb) gets a1111 to start but then adetailer no longer works.  has anyone figured out how to get that to work?

**Comment by TheLastBen** [comment]
fixed, use the latest notebook or add the following at the end of the dependencies cell (without installing any different wandb):
```
!sed -i 's@from pytorch_lightning.loggers.wandb import WandbLogger # noqa: F401@@g' /usr/local/lib/python3.11/dist-packages/pytorch_lightning/loggers/__init__.py
!sed -i 's@from .mailbox import ContextCancelledError@@g' /usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/retry.py
!sed -i 's@raise ContextCancelledError("retry timeout")@print("retry timeout")@g' /usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/retry.py
```

**Comment by TheLastBen** [comment]
fixed, use the latest notebook or add the following at the end of the dependencies cell (without installing any different wandb):

!sed -i 's@from pytorch_lightning.loggers.wandb import WandbLogger  # noqa: F401@@g' /usr/local/lib/python3.11/dist-packages/pytorch_lightning/loggers/__init__.py
!sed -i 's@from .mailbox import ContextCancelledError@@g' /usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/retry.py
!sed -i 's@raise ContextCancelledError("retry timeout")@print("retry timeout")@g' /usr/local/lib/python3.11/dist-packages/wandb/sdk/lib/retry.py

**Comment by mdlieber99** [comment]
something about this update leaves adetailer not working.  getting this in the terminal:

[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:335] Error parsing text-format mediapipe.CalculatorGraphConfig: 68:22: Expected identifier, got: \
[-] ADetailer: nothing detected on image 1 with 2nd settings.
[libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:335] Error parsing text-format mediapipe.CalculatorGraphConfig: 68:22: Expected identifier, got: \
[-] ADetailer: nothing detected on image 2 with 2nd settings.
INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 4 images in a total of 2 batches.

was working fine until the update

**Comment by Ardogg** [comment]
> something about this update leaves adetailer not working. getting this in the terminal:
> 
> [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:335] Error parsing text-format mediapipe.CalculatorGraphConfig: 68:22: Expected identifier, got: [-] ADetailer: nothing detected on image 1 with 2nd settings. [libprotobuf ERROR external/com_google_protobuf/src/google/protobuf/text_format.cc:335] Error parsing text-format mediapipe.CalculatorGraphConfig: 68:22: Expected identifier, got: [-] ADetailer: nothing detected on image 2 with 2nd settings. INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 4 images in a total of 2 batches.
> 
> was working fine until the update

pip install torch==2.1.0 torchvision==0.16.0

**Comment by olaviinha** [comment]
Yeah I too was still getting some (new) errors in the last cell, which the protobuf+wandb upgrade still seemed to solve.
