### ISSUE TITLE
ModuleNotFoundError: No module named 'py3d_tools'

### ISSUE THREAD

**Issue by riottrade** [TheLastBen/fast-stable-diffusion#399]
Hi, 

Running Deforum extension in your notebook. Image generation and everything works fine but when trying to generate animation I get this error :
ModuleNotFoundError: No module named 'py3d_tools'
Not sure how to fix this.

And also Open Image Directory don't work in whole notebook - text2image and image2image

<img width="647" alt="Screenshot 2022-11-05 at 16 40 17" src="https://user-images.githubusercontent.com/88867821/200128035-6fa75542-34bf-4677-a95e-0ec292910804.png">

**Comment by TheLastBen** [comment]
Create a new cell and run this code : 
```
import sys
%cd /content
!git clone https://github.com/MSFTserver/pytorch3d-lite.git
sys.path.append('./pytorch3d-lite')
```
see if it works so I'll add it to the notebook

**Comment by riottrade** [comment]
Didn't fix it. Same error. I updated Deforum and the rest of notebook runs smooth. Took me a while I restarted run time. I put the cell here :

<img width="647" alt="Screenshot 2022-11-05 at 17 38 20" src="https://user-images.githubusercontent.com/88867821/200131269-d9e7d228-d10d-495d-b263-fe6b4cee4550.png">


<img width="647" alt="Screenshot 2022-11-05 at 17 37 30" src="https://user-images.githubusercontent.com/88867821/200131216-16229726-dc6d-4f79-92b7-8ee6295d82ba.png">

**Comment by riottrade** [comment]
I added the Deforum extensions through webui and updated it.

**Comment by TheLastBen** [comment]
I'll try to find a solution

**Comment by riottrade** [comment]
Thx a lot. Adding this module to Requirments List didn’t help. Need to kick of those animations :)

**Comment by TheLastBen** [comment]
how did you install the extension ?

**Comment by riottrade** [comment]
Via the webui.

**Comment by TheLastBen** [comment]
fixed https://github.com/TheLastBen/fast-stable-diffusion/commit/6caa960f9c59e2a6e61a98e73cee26974b062e0f

**Comment by riottrade** [comment]
Will try it tomorrow. So now I just need to update the repo?

**Comment by TheLastBen** [comment]
no need to update the repo

**Comment by riottrade** [comment]
Afraid I still get the same result. module missing. I updated Deforum script. The cell you asked me to add is still there though..shall I try removing it?
this one : 
import sys
%cd /content
!git clone https://github.com/MSFTserver/pytorch3d-lite.git
sys.path.append('./pytorch3d-lite')

**Comment by TheLastBen** [comment]
did you update the colab to latest version ?

**Comment by riottrade** [comment]
to make that precise...your notebook or Deforum script dowloaded through webui ?

**Comment by TheLastBen** [comment]
If you don't want to refresh the collab, just copy the code from the "requirements" from the new notebook to your notebook

**Comment by riottrade** [comment]
Thank you Sir! It worked this time. Got first trial animation out just know. Respect!

**Comment by TheLastBen** [comment]
Great !

**Comment by jason-taylor-edi** [comment]
I am having the same error: ModuleNotFoundError: No module named 'py3d_tools'

What do I need to update exactly?

**Comment by TheLastBen** [comment]
use the latest colab : https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb

**Comment by jason-taylor-edi** [comment]
I still get the error.

**Comment by TheLastBen** [comment]
I'll check if something changed

**Comment by jason-taylor-edi** [comment]
When installing the requirements, in my google drive the deforum path is: 

/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/**deforum_helpers**/

but the requirements in the notebook check for this path:

/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/**deforum**/


Could this be anything to do with my issue? I've already redownloaded the sd repository.

**Comment by TheLastBen** [comment]
that must be it, the folder has changed, I'll fix it

**Comment by TheLastBen** [comment]
I did a superficial fix, can you show the folder structure of the directory "deforum_helpers"

**Comment by jason-taylor-edi** [comment]
<img width="361" alt="Screenshot 2022-11-17 at 22 39 19" src="https://user-images.githubusercontent.com/19727678/202575318-18f10ddf-b749-471e-a6b7-26f1f187d85b.png">

**Comment by TheLastBen** [comment]
Ok, the fix https://github.com/TheLastBen/fast-stable-diffusion/commit/bc3dddebfaef8cc970ac2fdea1030e211958471c should work

**Comment by yarabsahel** [comment]
I have the same obstacle; I even deleted the SD folder and started from scratch.

ModuleNotFoundError: No module named 'py3d_tools'
Time taken: 0.21sTorch active/reserved: 2069/2082 MiB, Sys VRAM: 3102/40537 MiB (7.65%)

**Comment by dvschultz** [comment]
same issues here. Looks like this is a known issue in the deforum tools. folder name should not be `deforum_helpers`, instead just `deforum`: https://github.com/deforum-art/deforum-for-automatic1111-webui/issues/80#issuecomment-1318395066

**Comment by cerarslan** [comment]
You are just amazing. I getting this erorr over and over so then I found this topic. I'll try it today and try to contribute here!

**Comment by jason-taylor-edi** [comment]
There is an if statement:

 if os.path.exists('/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/deforum/src/infer.py'):


Change the path to:

 if os.path.exists('/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/deforum-for-automatic1111-webui/scripts/**deforum_helpers**/src/infer.py'):

**Comment by TheLastBen** [comment]
I guess I forgot to change that part

**Comment by riottrade** [comment]
> I guess I forgot to change that part

Should we redownload the notebook?

**Comment by TheLastBen** [comment]
Yes

**Comment by yarabsahel** [comment]
> Yes

Thanks, it works now:) I wish you the best.

**Comment by yarabsahel** [comment]
I got this new error msg:
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.

Time taken: 0.29sTorch active/reserved: 2384/2588 MiB, Sys VRAM: 4296/40537 MiB (10.6%)

**Comment by TheLastBen** [comment]
after every fresh install, you will need to run the requirements cell

**Comment by yarabsahel** [comment]
> after every fresh install, you will need to run the requirements cell

Thank you

**Comment by TheLastBen** [comment]
> RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.

I don't think this error is related the the installation, more likely with the settings

**Comment by yarabsahel** [comment]
> > RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 24 but got size 23 for tensor number 1 in the list.
> 
> I don't think this error is related the the installation, more likely with the settings

Thanks, it works now, much appreciated:)

**Comment by riottrade** [comment]
Is there a way to save styles you saved in notebook? Fresh install erases them...or just copy somewhere and paste to freshly installed one?

**Comment by TheLastBen** [comment]
> copy somewhere and paste to freshly installed one?

that's the best solution

**Comment by riottrade** [comment]
Thanks a lot! Wanted to ask about Stable Diffusion V2. Does it have to be added to notebook from your side to download automaticaly during the load up?

**Comment by TheLastBen** [comment]
I'm working on reshaping the colab to support the V2, should be ready in a few hours

**Comment by riottrade** [comment]
Legend! Thanks for your hard work. Will check here and twitter dor updates. It seems to be quite an update!

**Comment by cerarslan** [comment]
> I'm working on reshaping the colab to support the V2, should be ready in a few hours

Omg! As I said before u are just amazing! Thx for everything.

**Comment by cerarslan** [comment]
I get same error again 😪. Anyone can explain step by step? :(

**Comment by riottrade** [comment]
I believe you need to re-download since Ben updated collab for Stable V2...and possibly update Deforum extension. My guess.

**Comment by cerarslan** [comment]
> I believe you need to re-download since Ben updated collab for Stable V2...and possibly update Deforum extension. My guess.

Not working :/
