### ISSUE TITLE
Trying to load depth2img extension on colab

### ISSUE THREAD

**Issue by Subaru17** [TheLastBen/fast-stable-diffusion#750]
Error loading script: depthmap_for_depth2img.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/depthmap2mask/scripts/depthmap_for_depth2img.py", line 11, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'repositories'

**Comment by TheLastBen** [comment]
the problem with the extensions devs is that they use hardcoded paths instead of calling paths.py of the webui.

**Comment by Maxxxwell62** [comment]
> Im using this colab version running 1.5 model: https://colab.research.google.com/github/TheLastBen/fast-stable-diffusion/blob/main/fast_stable_diffusion_AUTOMATIC1111.ipynb
> 
> Error loading script: depthmap_for_depth2img.py Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts module = script_loading.load_module(scriptfile.path) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module exec(compiled, module.**dict**) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/depthmap2mask/scripts/depthmap_for_depth2img.py", line 11, in from repositories.midas.midas.dpt_depth import DPTDepthModel ModuleNotFoundError: No module named 'repositories'


try to put this cell after installing Automatic 1111 repo:

#@markdown # (Optional) Install Depth Map Script
%pwd
%pushd .
%cd ./scripts
!wget https://raw.githubusercontent.com/thygate/stable-diffusion-webui-depthmap-script/main/depthmap.py
%popd
!pwd
!git clone https://github.com/isl-org/MiDaS.git repositories/midas

**Comment by Subaru17** [comment]
> Maxxxwell62
This is what i get
Error loading script: tag_autocomplete_helper.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 89, in <module>
    write_tag_base_path()
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 64, in write_tag_base_path
    f.write(TAGS_PATH.relative_to(FILE_DIR).as_posix())
  File "/usr/lib/python3.7/pathlib.py", line 900, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/tags' does not start with '/content/gdrive/MyDrive/sd/stablediffusion'

Error loading script: api.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module
    compiled = compile(text, path, 'exec')
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 14
    db_half_model: bool = False,

**Comment by Maxxxwell62** [comment]
> > Maxxxwell62
> > This is what i get
> > Error loading script: tag_autocomplete_helper.py
> > Traceback (most recent call last):
> > File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
> > module = script_loading.load_module(scriptfile.path)
> > File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
> > exec(compiled, module.**dict**)
> > File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 89, in 
> > write_tag_base_path()
> > File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/scripts/tag_autocomplete_helper.py", line 64, in write_tag_base_path
> > f.write(TAGS_PATH.relative_to(FILE_DIR).as_posix())
> > File "/usr/lib/python3.7/pathlib.py", line 900, in relative_to
> > .format(str(self), str(formatted)))
> > ValueError: '/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/a1111-sd-webui-tagcomplete/tags' does not start with '/content/gdrive/MyDrive/sd/stablediffusion'
> 
> Error loading script: api.py Traceback (most recent call last): File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts module = script_loading.load_module(scriptfile.path) File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 11, in load_module compiled = compile(text, path, 'exec') File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd_dreambooth_extension/scripts/api.py", line 14 db_half_model: bool = False,


i don't know how to fix it

**Comment by wilzamguerrero** [comment]
Hi run this, with this have to run you dont have warnings for start.

import os
SD_webui_path = "/content/gdrive/MyDrive/sd/stable-diffusion-webui" #@param {type:"string"}
os.chdir(SD_webui_path)

%cd extensions
!git clone https://github.com/Extraltodeus/depthmap2mask.git

%cd ..
!mkdir repositories
%cd repositories
!git clone https://github.com/isl-org/MiDaS.git


And later you can see the extension in the webui, but you find other problem like this and i dont find solution yet

 File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 859, in get_code
  File "<frozen importlib._bootstrap_external>", line 916, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'extensions/depthmap2mask/scripts/depthmap_for_depth2img.py'

**Comment by TheLastBen** [comment]
fixed

**Comment by wilzamguerrero** [comment]
Thank you, TheLastBen i can write for private, i know that have many work with this and many issues but if you have time please look this link, https://github.com/wilzamguerrero/SDZ

**Comment by xaviersingy** [comment]
Thanks ; note though that this extension is not depth2image but depthmap2mask.

**Comment by Subaru17** [comment]
still cant load @TheLastBen 

Error loading script: depthmap_for_depth2img.py
Traceback (most recent call last):
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/scripts.py", line 184, in load_scripts
    module = script_loading.load_module(scriptfile.path)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/modules/script_loading.py", line 13, in load_module
    exec(compiled, module.__dict__)
  File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/depthmap2mask/scripts/depthmap_for_depth2img.py", line 11, in <module>
    from repositories.midas.midas.dpt_depth import DPTDepthModel
ModuleNotFoundError: No module named 'repositories.midas'

**Comment by TheLastBen** [comment]
fixed
