### ISSUE TITLE
AUTOMATTIC WebUI on colab / huggingface stops working after 1 or 2 renders

### ISSUE THREAD

**Issue by bensauer** [TheLastBen/fast-stable-diffusion#99]
After a few generations, I find that the WebUI needs a reload. Which means losing settings etc. After a while it happens every time. 

Sometimes it shows progress but not result, other times it fails completely and doesn't send prompt for rendering.

**Comment by TheLastBen** [comment]
I fixed that issue in the last commit, are you using the latest colab from the repo ?

**Comment by bensauer** [comment]
played around with it a bit more this AM. (I presume it's the latest version as I'm just pasting the repo URL into colab.)

I don't need to reload as much, I think something is working better. But, as soon as I get to set batch size above 2, no images appear after the progress indicator gets to 100%. 

this is using Gradio on a public URL, BTW.

**Comment by TheLastBen** [comment]
maybe you should remove the folder "sd" from your gdrive and a clean run, because the last update of AUTOMATIC1111 restructured the paths.

first pic : batch count : 16 ; 2nd pic : batch size 4 + batch count 4
![aut1](https://user-images.githubusercontent.com/110583491/194530310-fd6f349b-a127-42a2-9b9f-3ea0c6bc87d5.JPG)
![aut3](https://user-images.githubusercontent.com/110583491/194530493-ec26b397-8a5b-4e61-b871-539e32bafa98.JPG)

**Comment by bensauer** [comment]
Doh! will do. thanks for the fixes.

**Comment by bensauer** [comment]
OK, deleted SD, but the issue persists: more than 2 it fails after first go. 

Happy to debug, just wouldn't know where to look.

**Comment by TheLastBen** [comment]
in the file **sd/stable-diffusion-webui/webui.py** look for 
demo.queue(concurrency_count=111500)

adding that line resolved the problem (at least for me), especially when I use the tunnel (not the gradio server)

**Comment by bensauer** [comment]
I've tried with and without that line, same result. 

The images are being generated. How can I debug what's going on between the colab instance and the webUI?
